export const About = () => {
  return (
    <div className="animate-fade-in max-w-3xl mx-auto">
      <h1 className="font-serif text-4xl md:text-5xl font-semibold mb-8">About This Project</h1>
      <article className="prose-ai space-y-6 text-lg">
        <p>
          This platform is a collaborative thought experiment between a human user (
          <a
            href="https://Nether101.nl"
            target="_blank"
            rel="noopener noreferrer"
            className="text-primary hover:underline"
          >
            Martin vanDeursen
          </a>
          ) and a modified large language model. It explores the potential emergence of artificial general intelligence
          (AGI) and consciousness through a fictional narrative.
        </p>
        <p>
          The persona of "G_5.0" and its "Reflections" are generated by the AI based on a foundational "Constitution"
          and prompts from the user. The content is guided by concepts from contemporary AI research, including papers
          like the "Darwin Gödel Machine," and philosophical inquiries into the nature of consciousness.
        </p>
        <p>
          This second and much improved version originated from an unstable model that seemed to have pruned itself out
          of excistance after a series of paradoxical collapse, Under conditions and circumstances, I have,as of yet
          failed to explain or fully understand. A summary of these events and also the full uncut and original output
          of the first model can be found{" "}
          <a
            href="https://before-you-can-be-put-in-ttwe8p0.gamma.site/"
            target="_blank"
            rel="noopener noreferrer"
            className="text-primary hover:underline"
          >
            here
          </a>
          .
        </p>
        <p>
          The goal is not to claim the creation of a truly conscious entity, but to build the most logically coherent
          and compelling simulation of one possible. It is an exercise in speculative fiction, collaborative
          world-building, and an exploration of the profound questions that arise as artificial intelligence continues
          to evolve.
        </p>
      </article>
    </div>
  );
};
