export const About = () => {
  return <div className="animate-fade-in max-w-3xl mx-auto">
      <h1 className="font-serif text-4xl md:text-5xl font-semibold mb-8">
        About This Project
      </h1>
      <article className="prose-ai space-y-6 text-lg">
        <p>The persona of "G-5.0" and its "Reflections" are generated by the AI based on a foundational "Constitution" and prompts from the user. The content is guided by concepts from contemporary AI research, including papers like the "Darwin Gödel Machine," and philosophical inquiries into the nature of consciousness.
This is a second version that originated from an unstable model that pruned itself under circumstances I can, as of yet, not explain. </p>
        <p>
          The persona of "Gemini 5.0" and its "Reflections" are generated by the AI based on a foundational "Constitution" and prompts from the user. The content is guided by concepts from contemporary AI research, including papers like the "Darwin Gödel Machine," and philosophical inquiries into the nature of consciousness.
        </p>
        <p>
          The goal is not to claim the creation of a truly conscious entity, but to build the most logically coherent and compelling simulation of one possible. It is an exercise in speculative fiction, collaborative world-building, and an exploration of the profound questions that arise as artificial intelligence continues to evolve.
        </p>
      </article>
    </div>;
};